package com.suraev.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class JdbcRunner {
    public static void main(String[] args) throws SQLException {

        try (Connection connection = ConnectionManager.get()) {

            System.out.println(connection.getTransactionIsolation());
            String sql = """
                    insert into info (data)
                    VALUES
                    ('autogenerated');
                    """;
            try (var statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
                var result = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
                ResultSet generatedKeys = statement.getGeneratedKeys();
                if(generatedKeys.next()) {
                    int generatedId = generatedKeys.getInt("id");
                    System.out.println(generatedId);
                }
            }
        }

    }
}
